---
# tasks file for postgresql-ocp

- name: Set OpenShift Objects for Postgresql to {{ _postgresql_state }}
  community.kubernetes.k8s:
    state: "{{ _postgresql_state }}"
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
  - secret.yaml.j2
  - service.yaml.j2
  - persistent_volume_claim.yaml.j2
  - deployment.yaml.j2

- name: Wait until application is available
  when:
    - _postgresql_state == "present"
    - _postgresql_wait_for_init|bool
  community.kubernetes.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: "{{ _postgresql_name }}"
    namespace: "{{ _postgresql_namespace }}"
  register: r_deployment
  until:
  - r_deployment.resources[0].status.availableReplicas is defined
  - r_deployment.resources[0].status.availableReplicas == 1
  retries: 50
  delay: 10
